name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # 1. Checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Seleciona versão do Xcode (garante compatibilidade)
      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      # 3. Cache (compilações + SwiftPM)
      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            .build
          key: ${{ runner.os }}-xcode-${{ hashFiles('**/*.swift') }}
          restore-keys: |
            ${{ runner.os }}-xcode-

      # 4. Lista simuladores disponíveis (debug visual)
      - name: List Simulators
        run: xcrun simctl list devices

      # 5. Build for Testing
      - name: Build for Testing
        run: |
          xcodebuild \
            -project "PokedexProject.xcodeproj" \
            -scheme "PokedexProject" \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -enableCodeCoverage YES \
            clean build-for-testing \
            | xcpretty

      # 6. Test (without building)
      - name: Run Tests
        run: |
          xcodebuild \
            -project "PokedexProject.xcodeproj" \
            -scheme "PokedexProject" \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -enableCodeCoverage YES \
            test-without-building \
            | xcpretty
